name: Issue Notification Pipeline
on: [issues,workflow_dispatch]
jobs:
  issuelog:
    runs-on: ubuntu-latest
    steps:
    - name: issuelogger
      run: echo ${{ toJSON(github.event) }}
    
     
