name: Build Pipeline
on: workflow_dispatch
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: InstallNode
      uses: actions/checkout@v3
    - name: Checkout complete
      run:  echo " Checkout Complete"

  installnode: 
    needs: checkout
    runs-on: ubuntu-latest
    steps:
    - name: InstallNode
      uses: actions/checkout@v3
    - name: Install Nodes
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: "Install dependencies"
      run: npm ci   
    - name: "install complete"
      run: echo "Installation of Nodejs Complete.. "

  linting:
    needs: installnode
    runs-on: ubuntu-latest
    steps:
    - name: Install Node
      uses: actions/checkout@v3
    - name: Install Nodes
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Linting the Project 
      run: npm i --save-dev eslint

  testing:
    needs: linting
    runs-on: ubuntu-latest
    steps:
    - name: Install Node
      uses: actions/checkout@v3
    - name: Install Nodes
      uses: actions/setup-node@v3
    - name: Install dependencies
      run: npm ci
    - name: Linting the Project 
      run: npm lint
    - name: testing the Project
      run: npm test
    - name: Testing complete
      run: " Testing completed"
  
  build:
    needs: testing
    runs-on: ubuntu-latest
    steps:
    - name: Install Node
      uses: actions/checkout@v3
    - name: Install Nodes
      uses: actions/setup-node@v3
    - name: Install dependencies
      run: npm ci
    - name: Linting the Project 
      run: npm lint
    - name: testing the Project
      run: npm test
    - name: Testing complete
      run: " Testing completed"

  info:
    runs-on: ubuntu-latest
    steps:
    - name: Install Node
      uses: actions/checkout@v3
    - name: Install Nodes
      uses: actions/setup-node@v3
    - name: Install dependencies
      run: npm ci
    - name: Linting the Project 
      run: npm lint
    - name: testing the Project
      run: npm test
    - name: Testing complete
      run: " Testing completed"
    - name: "Display the info"
      run: echo {{$toJOSN(github)}}

  
  
      
